version: '3.9'

services:
  interactive-segmentation:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/bioimage-io/bioimageio-colab:latest
    env_file:
      - .env
    command: ["--token", "${HYPHA_TOKEN}"]
