version: '3.9'

services:
  bioimageio-colab:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: bioimageio-colab-model:latest
    environment:
      USER_TOKEN: ${USER_TOKEN}
