version: '3.9'

services:
  interactive-segmentation:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bioimage-io/bioimageio-colab:latest
    env_file:
      - .env
    command: [
      "--server_url=https://hypha.aicell.io",
      "--workspace_name=bioimageio-colab",
      "--service_id=microsam",
      "--cache_dir=/tmp/ray/.model_cache",
      "--skip_test_runs",
      "--max_concurrent_requests=3",
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
    shm_size: 10.24gb
    volumes:
      - /data/tmp/ray:/tmp/ray
