version: '3.9'

services:
  interactive-segmentation:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bioimage-io/bioimageio-colab:latest
    env_file:
      - .env
    command: [
      "--server_url=https://hypha.aicell.io",
      "--workspace_name=bioimageio-colab",
      "--service_id=microsam",
    ]
